/*
  Painel Loja Integrada > Códigos HTML
  Descrição: script-nomes-2.js (código 2 de 2: 2ª metade da lista)
  Local publicação: Rodapé | Página: Todas as páginas exceto checkout | Tipo: JavaScript
  Usada por: script-nomes-1.js (a troca dos nomes)
*/
// Lista: código → [nome, linha técnica]. Produto fora da lista mantém o nome normal.
window.UK_NOMES = Object.assign(window.UK_NOMES || {}, {
    "CV-2BI-181-VT-2VPB": ["Adega Vetro 181 Garrafas","Built-In (Embutir) | Dual Zone | Acabamento em Vidro Preto | 220V"],
    "CBK401B": ["Churrasqueira a Gás Modena 34\"","3 Queimadores + Sear Zone + Infrared | 75.000 BTUs | Inox 304"],
    "CV-2BI-87-VT-2VPA": ["Adega Vetro 87 Garrafas","Built-In (Embutir) | Dual Zone | Acabamento em Vidro Preto | 220V"],
    "CBK200": ["Churrasqueira a Gás Capri","2 Queimadores | Inox 304 | 24.000 BTUs | 55cm"],
    "CFD-SOL-90-XV-2ATC": ["Coifa Sollevare Connect","90cm | Downdraft (Bancada) | Wi-Fi | Inox e Vidro Preto | 220V"],
    "DBQ-IR-40-XX-NHUA": ["Dominó Churrasqueira Infrared 40cm","Design Professional | 15.000 BTUs | Inox 304 | Built-In"],
    "CBY200SB": ["Side Burner a Gás","2 Queimadores | Inox 304 | 27.000 BTUs | Bivolt"],
    "CBK301M": ["Churrasqueira a Gás Verona","3 Queimadores + Infrared | 48.000 BTUs | Inox 304 | 69cm"],
    "CFI-MLN-90-XX": ["Coifa de Ilha Milano","90cm | 1.200 m³/h | Inox | 4 Velocidades | 220V"],
    "CFI-MLN-120-XX-2ATA": ["Coifa de Ilha Milano","120cm | 1.200 m³/h | Inox | 4 Velocidades | 220V"],
    "CKG-4Q-60-XQ-3ZEA": ["Cooktop a Gás Quadratto","4 Queimadores | 60cm | Dual Flame | Inox 304 | Suporte Wok"],
    "CFI-MOB-90-VP-2ATC": ["Coifa Mobile Built-in Connect","90cm | Embutir em Armário | Wi-Fi | Vidro Preto | 220V"],
    "ECTGD5QM3A": ["Cooktop a Gás 87cm","5 Queimadores | Inox 304 | Gás Stop | Bivolt"],
    "GW951X-BR": ["Cooktop a Gás 90cm","5 Queimadores | Queimador Wok | Inox | 220V"],
    "EFGGF6QM2A": ["Fogão Profissional a gás 36\"","6 Queimadores | Forno 163L | Air Fry | Inox 304 | 220V"],
    "MAS604GGEVSXE": ["Fogão Bertazzoni Master","60cm | 4 Queimadores a Gás | Forno Turbo Ventilado a Gás 60L | Grill Infravermelho"],
    "MAS604GMFESXE": ["Fogão Bertazzoni Master","60cm | 4 Queimadores a Gás | Forno Elétrico Ventilado 60L | Grill Infravermelho"],
    "FGG-5Q-90-XP-2GMA": ["Fogão Professional Gás/Gás 90cm","5 Queimadores | Forno a Gás 116L | Dual Fan | Inox 304 | 220V"],
    "FGG-6Q-36-XP-1SGA": ["Fogão Professional 36\"","6 Queimadores | Forno a Gás 127L | Inox 304 | 127V"],
    "FGE-5Q-90-XP-2GMA": ["Fogão Professional Gás/Elétrico 90cm","5 Queimadores | Forno Elétrico 116L | Dual Fan | Inox 304 | 220V"],
    "FGG-8Q-48-XP-1SGA": ["Fogão Professional Gás/Gás 48\"","8 Queimadores | Forno Duplo (100L + 56L) | Inox 304 | 127V"],
    "FG-AN-60-LC-2TNA": ["Forno Luce a Gás 60cm","Inox | 68 Litros | 220V | Convecção"],
    "BOS6747A01XBR": ["Forno Multifunção 60cm","77 Litros | AirFry | Pizza 300°C | Inox | 220V"],
    "EFNEB0352A": ["Forno Elétrico 73L IX13","Air Fryer | Embutir | 220V | Inox e Vidro Preto"],
    "FM-EL-60-LC-2TNA": ["Forno Multifunção Luce 60cm","Elétrico | 68 Litros | 11 Funções | Inox 304 | 220V"],
    "FM-EL-75-LC-2TNA": ["Forno Multifunção Luce 75cm","Elétrico | 78 Litros | 12 Funções | Inox 304 | 220V"],
    "FM-EL-60-VT-2TNA": ["Forno Multifunção Vetro 60cm","Elétrico | 68 Litros | 12 Funções | Vidro Preto | 220V"],
    "BM321A7X-BR": ["Micro-ondas Combinado 32L BM321A7X","Inox | Convecção | Grill | 220V"],
    "EMCEB0352A": ["Micro-ondas Combinado 35L IX13","Inox e Vidro Preto | Convecção | Grill | 220V"],
    "EMCEB0352B": ["Micro-ondas Combinado 35L IX17","Inox e Vidro Preto | Convecção | Grill | 220V"],
    "FMC-LT-25-LC-2GZB": ["Micro-ondas Luce Flat 23L","Inox e Vidro Preto | Tecnologia Flat | Grill | 220V"],
    "FMC-LT-25-VT-2GZA": ["Micro-ondas Vetro Flat 23L","Tecnologia Flat | Sem Prato Giratório | Grill | 220V"],
    "EMOEB0252B": ["Micro-ondas 25L C17","Embutir | Grill | Inox e Vidro Preto | 220V"],
    "EGAEB0062A": ["Gaveta Aquecida IX17 60cm","Inox e Vidro Preto | 6 Serviços | Push Open | 220V"],
    "GA-12S-30-XX-2TNA": ["Gaveta Aquecida Inox 30cm","12 Serviços | Push Pull | Built-In | 220V"],
    "EGAEB0062B": ["Gaveta Aquecida IX13 60cm","Inox 304 | 6 Serviços | Push Open | 220V"],
    "GA-6S-14-XX-2TNA": ["Gaveta Aquecida Inox 14cm","6 Serviços | Push Pull | Built-In | 220V"],
    "FR-LL-45-XX-NCLA": ["Frente para Lava-louças 10S","Aço Inox 304 | Puxador Original | Para Modelo 45cm"],
    "FR-LL-60-XX-NCLB": ["Frente para Lava-louças","Aço Inox 304 | Puxador Original | Para Modelo 14 Serviços"],
    "LL-10S-45-SR-2VSA": ["Lava-louças 10 Serviços","Para Revestir | Built-In | 45cm | 220V"],
    "TD14EXDO": ["Lava-louças Original 14 Serviços","Inox 304 | Built-In (Embutir) | Silenciosa | 220V"],
    "TD14EXDP": ["Lava-louças Professional 14 Serviços","Inox 304 | Built-In (Embutir) | Puxador Tubular | 220V"],
    "TD14WP": ["Lava-louças de Embutir 14 Serviços","Para Revestir | Built-In | Silenciosa | 220V"],
    "GV693C60UVBR": ["Lava-louças SmartFlex 16S","Para Revestir | UV Technology | ConnectLife | 220V"],
    "ELLER0152A": ["Lava-louças 15 Serviços","Para Revestir | Built-In | Projeção no Piso | 220V"],
    "TR10FZDA": ["Freezer 100L Professional","Inox 304 | 2 Gavetas | Embutir ou Piso | 220V"],
    "FZ-DU-307-XX-2VSA": ["Freezer Duo 307L","Inox | No Frost | 220V | Metal Cooling"],
    "ESPLL0001": ["Painel Decorativo para Lava-Louças","Inox 304 | Puxador Incluso | Compatível com Modelo 14 Serviços"],
    "FNI5182A1": ["Freezer Vertical de Embutir","Built-in (Revestir) | NoFrost | Inverter | 220V"],
    "TR14BVDB": ["Frigobar 136L Professional","Inox | Embutir ou Piso | Abertura Esquerda | 220V"],
    "RI5182A1": ["Refrigerador de Embutir RI5182A1","Para Revestir | Inverter | AdaptTech | 305 Litros"],
    "NRKI5182A2": ["Refrigerador de Embutir NRKI5182A2","Para Revestir | Inverter | NoFrost DualAdvance | 220V"],
    "RF-BF-510-XX-2VSA": ["Refrigerador Inox Bottom Freezer 510L","Inox | Freestanding/Built-In | Inverter | 220V"],
    "RF-DU-404-XX-2VSA": ["Refrigerador Duo 404L","Inox | Conceito Duo | Ion Tech | 220V"],
    "GRF-49W": ["Refrigerador French Door 466L","Instalação Livre | Aço Inox | ConvertZone | 220V"],
    "ERDEB5042A": ["Refrigerador Multi Door 504L","Smart Wi-Fi | Inox 304 | Built-In (Embutir) | 220V"],
    "08326": ["Dosador de Sabão Cromado","250ml | Abastecimento Superior | Alto Brilho"],
    "DE-BQ-30-XQ-2ZEA": ["Dominó Barbecue Quadratto 30cm","Elétrico | Pedras Vulcânicas | Inox 304 | Built-In | 220V"],
    "DFD72EXB": ["Painel Decorativo para Lava-Louças","Inox Escovado | Linha HomeMade | Puxador Incluso"],
    "FAB28RDGC5": ["Refrigerador Smeg Dolce & Gabbana","Coleção Divina Cucina | 270L | 220V | Abertura Direita"],
    "FAB28RBE5": ["Refrigerador Anni 50 Azul","270L | Instalação Livre | 220V | Abertura Direita"],
    "TWD60EXDP": ["Wine Dispenser Enoteca","3 Garrafas | Preservação por Argônio | Inox e Vidro Espelhado | 220V"],
    "THV30BBQ": ["Cooktop Dominó Barbecue","Elétrico | Pedras Vulcânicas | Vitrocerâmico | 30cm | 220V"],
    "THV30TEPPAN": ["Cooktop Dominó Teppan Yaki","Chapa Inox 304 | Vitrocerâmico | 2 Zonas | 220V"],
    "TR08HC": ["Umidor de Charutos 80L","Inox 304 | 500 Charutos | Embutir ou Piso | 220V"],
    "TR14CVDC": ["Cervejeira 136L Professional","136 Litros | Abertura Esquerda | Built-In (Embutir) | 220V"],
    "TR14CVDD": ["Cervejeira 136L Professional","136 Litros | Abertura Direita | Built-In (Embutir) | 220V"],
    "THV30FRYER": ["Cooktop Dominó Fryer","Fritadeira & Cozedor | Inox 304 | Built-In | 220V | 30cm"],
    "TR14CRDD": ["Cervejeira Professional de Revestir","136 Litros | Panel Ready | Abertura Direita | 220V"],
    "TIM50EXDA": ["Máquina de Gelo 50kg Professional","Inox 304 | Bomba de Drenagem | Luz UV | 220V"],
    "JG36I": ["Ice Maker Smart 20kg","Inox 304 | Wi-Fi | Gelo Cristal | 220V"],
    "TR08CVDA": ["Cervejeira 80L Professional","80 Litros | Compacta 38cm | Abertura Esquerda | 220V"],
    "BC-BI-144-VT-2VPA": ["Beer Center Vetro 144 Litros","Built-In (Embutir) | Acabamento em Vidro Preto | 220V"],
    "ECFEP0902B": ["Coifa Smart de Parede Zeta 90cm","Inox 304 | Filtro de Alumínio | Wi-Fi | 220V"],
    "JC-145C": ["Beer Center Smart 135L","Built-In (Embutir) | Modo Festa -9ºC | Wi-Fi | 127V ou 220V"],
    "ECFEP0702A": ["Coifa Smart de Parede Tau 70cm","Inox 304 | Filtro Baffle Profissional | Wi-Fi | 220V"],
    "ECFEI0382A": ["Coifa Tubular de Ilha 38cm","Smart (Wi-Fi) | Inox 304 | Linha Ômicron | 220V"],
    "ECFEI0902A": ["Coifa Smart de Ilha Delta 90cm","Inox 304 | Filtro Baffle Profissional | Wi-Fi | 220V"],
    "ECFEP0902A": ["Coifa Smart de Parede Sigma 90cm","Inox 304 e Vidro Preto | Filtro Baffle | Wi-Fi | 220V"],
    "ECFEI0902B": ["Coifa Smart de Ilha Sigma 90cm","Inox 304 e Vidro Preto | Filtro Baffle | Wi-Fi | 220V"],
    "CKG-5Q-70-VT-3TNB": ["Cooktop Vetro 70cm","5 Queimadores | Dual Flame | Vidro Preto | 220V"],
    "IS846BG": ["Cooktop de Indução OmniFlex","80cm | AreaFlex | SliderTouch Groove | 220V"],
    "CKG-4Q-60-VT-3TNA": ["Cooktop Vetro 60cm","4 Queimadores | Dual Flame | Vidro Preto | Bivolt"],
    "CKG-5Q-90-VT-3TNA": ["Cooktop Vetro 90cm","5 Queimadores | Dual Flame | Vidro Preto | 220V"],
    "THV90L2": ["Cooktop a Gás Tecno 90cm Vitrocerâmico","5 Queimadores | Dual Flame 5.500W | Vidro Espelhado | 220V"],
    "CKG-5Q-75-XQ-3ZEA": ["Cooktop a Gás Quadratto 75cm","5 Queimadores | Dual Flame | Inox 304 | Suporte Wok | 220V"],
    "DG-2Q-30-XQ-3ZEA": ["Dominó Quadratto 2 Queimadores","30cm | Inox 304 | Gás Stop | Built-In | 220V"],
    "CKG-5Q-90-XQ-3ZEA": ["Cooktop a Gás Quadratto 90cm","5 Queimadores | Dual Flame | Inox 304 | Suporte Wok | 220V"],
    "ECTID4QM2A": ["Cooktop de Indução 60cm","4 Zonas | Zona Flex (Bridge) | Smart (Wi-Fi) | 220V"],
    "ECTID5QM2A": ["Cooktop de Indução 90cm","5 Zonas | Zona Flex (Bridge) | Smart (Wi-Fi) | 220V"],
    "THV30DFL": ["Cooktop Dominó a Gás","1 Queimador Dual Flame | Mesa Vitrocerâmica | 30cm | 220V"],
    "CKG-5Q-90-LC-3ZEA": ["Cooktop a Gás Luce 90cm","5 Queimadores | Step Flame | Inox 304 | Trempes Contínuas | 220V"],
    "ECTGD2QM3A": ["Cooktop a Gás Siena 2Q","Dominó 29cm | 1 Tripla Chama | Inox 304 | Gás Stop"],
    "CKG-5Q-75-LC-3ZEA": ["Cooktop a Gás Luce 75cm","5 Queimadores | Step Flame | Inox 304 | Trempes Contínuas | 220V"],
    "CKG-4Q-60-LC-3ZEA": ["Cooktop a Gás Luce 60cm","4 Queimadores | Step Flame | Inox 304 | Trempes Contínuas | 220V"],
    "DG-1Q-30-XQ-3ZEA": ["Dominó Quadratto Dual Flame 30cm","1 Queimador | Dual Flame (4.0kW) | Inox 304 | Built-In | 220V"],
    "1007-QUA-8-INX": ["Lixeira Quadrada com Sensor 8L","Abertura Automática sem Toque | Acabamento Inox | Linha Suprema"],
    "ECTGD4QM3C": ["Cooktop Black Glass","4 Queimadores | 2 Tripla Chama | LED | 87cm | Bivolt"],
    "BCM4547A10XBR": ["Forno Combinado com Micro-ondas 50L","Inox | Essential Line | Inverter | Stirrer | 220V"],
    "09888": ["Lixeira Redonda 12L","Inox Escovado | De Embutir | Grande Capacidade"],
    "Insinkerator1000SR": ["Triturador Evolution Plus 1000 SR","1 HP | 4 Estágios de Trituração | Ultra Silencioso | 127V ou 220V"],
    "AC-300-TRI": ["Triturador de Resíduos de Alimentos Deca","3/4 HP | Componentes em Aço Inox | Acionamento Pneumático | 127V ou 220V"],
    "Insinkerator750SR": ["Triturador Evolution Plus 750 SR","0,75 HP | Ultra Silencioso | 2 Estágios de Trituração | 127V ou 220V"],
    "RF-BF-510-VT-2VSA": ["Refrigerador Vetro Bottom 510L","Vidro Preto | Built-In (Embutir) | Inverter | No Frost"],
    "Insinkerator460": ["Triturador Standard 460","0,55 HP | 1 Estágio de Trituração | Capacidade de 980ml | 127V ou 220V"],
    "Insinkerator700SR": ["Triturador Premium 700 SR","0,75 HP | 2 Estágios de Trituração | Câmara Inox 980ml | 127V ou 220V"],
    "Insinkerator550SR": ["Triturador Premium 550 SR","0,55 HP | 2 Estágios de Trituração | Câmara Inox 980ml | 127V ou 220V"]
});
